wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 10
eta:
  value: 0.0005830912133361339
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
