wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
eta:
  value: 0.0009986271113108446
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: nadam
weight_decay:
  value: 0.0001
weight_init:
  value: random
