wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 16
epochs:
  value: 40
eta:
  value: 0.0008346978185282515
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: random
