program: sweep_train.py
method: random
metric:
  name: validation_accuracy
  goal: maximize
parameters:
  eta:
    min: 0.0001
    max: 0.001
  optimizer:
    values: ['sgd', 'momentum', 'nag', 'rmsprop', 'adam', 'nadam']
  activation:
    values: ['tanh', 'ReLu']
  epochs:
    values: [25,40,50]
  batch_size:
    values: [16,32,64,128]
  num_layers: 
    values: [2,3,4]
  hidden_size: 
    values: [16, 32, 64] 
  weight_init: 
    values: ['random', 'Xavier']
  weight_decay: 
    values: [0.0, 0.0]
