wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.0007973753606224757
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
