wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 40
eta:
  value: 0.0005273517782578986
hidden_size:
  value: 16
num_layers:
  value: 2
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: random
