wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 40
eta:
  value: 0.0004029533736131022
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: Xavier
