wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 40
eta:
  value: 0.0008249860432683378
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
