wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.0008956773827151668
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
