wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 16
epochs:
  value: 40
eta:
  value: 0.0008900892833089781
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: Xavier
