wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 32
epochs:
  value: 40
eta:
  value: 0.0007735482124165069
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 0.0001
weight_init:
  value: random
