wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 32
epochs:
  value: 20
eta:
  value: 0.00015028444703716178
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: random
