wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 40
eta:
  value: 0.0006368744616176566
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
