wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 10
eta:
  value: 0.0008773812489294544
hidden_size:
  value: 32
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0.0001
weight_init:
  value: random
