wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.00012001044003108748
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: Xavier
