wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 32
epochs:
  value: 10
eta:
  value: 0.0007137334222954303
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
