wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 40
eta:
  value: 0.0004334496264758012
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
