wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 40
eta:
  value: 0.00033806096234341356
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: Xavier
