wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 50
eta:
  value: 0.0009573439534157728
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: Xavier
