wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 50
eta:
  value: 0.00013297108680856252
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
