wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 16
epochs:
  value: 50
eta:
  value: 0.000521347888733774
hidden_size:
  value: 16
num_layers:
  value: 2
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: Xavier
