wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 25
eta:
  value: 0.000995755401719532
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
