wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 50
eta:
  value: 0.0008085995490907296
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: random
