wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 16
epochs:
  value: 40
eta:
  value: 0.00018271384269531176
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
