wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.0003649828315166458
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: random
