wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 20
eta:
  value: 0.00037034411314239665
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: Xavier
