wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 40
eta:
  value: 0.0008177623593812779
hidden_size:
  value: 32
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
