wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.00039669049444935385
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
