wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 32
epochs:
  value: 20
eta:
  value: 0.0008303858414103504
hidden_size:
  value: 16
num_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: random
