wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 16
epochs:
  value: 20
eta:
  value: 0.0006455219894165523
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: nag
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
