wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 20
eta:
  value: 0.0009210313529384556
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: random
