wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
eta:
  value: 0.00017351272194689974
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
