wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 40
eta:
  value: 0.0003978639374054349
hidden_size:
  value: 16
num_layers:
  value: 2
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: Xavier
