wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 25
eta:
  value: 0.0006588420571538419
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: random
