wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 32
epochs:
  value: 50
eta:
  value: 0.0002684896953361593
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: random
