wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 128
epochs:
  value: 50
eta:
  value: 0.0002586246277779888
hidden_size:
  value: 16
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
