wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 16
epochs:
  value: 50
eta:
  value: 0.0004690011636725432
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
