wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 32
epochs:
  value: 40
eta:
  value: 0.00041342749132936994
hidden_size:
  value: 16
num_layers:
  value: 2
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
