wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 25
eta:
  value: 0.0004926152900724551
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
