wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 50
eta:
  value: 0.0004563286651071821
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: Xavier
