wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 128
epochs:
  value: 25
eta:
  value: 0.0008351678638257983
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: Xavier
