wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 50
eta:
  value: 0.00028435872918096026
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
