wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 50
eta:
  value: 0.000559620495037855
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: random
