wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 50
eta:
  value: 0.0008835605222549379
hidden_size:
  value: 16
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: Xavier
