wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 16
epochs:
  value: 50
eta:
  value: 0.0005072148077652814
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
