wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 25
eta:
  value: 0.0003286605424962813
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: random
