wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 40
eta:
  value: 0.00019165334287996955
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
