wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 40
eta:
  value: 0.00027531396097747225
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
