wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 50
eta:
  value: 0.0007626592018396345
hidden_size:
  value: 32
num_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: random
