wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 64
epochs:
  value: 40
eta:
  value: 0.0004725798586959514
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: Xavier
