wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.19.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744344168
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 14
      - 23
      - 37
      4: 3.12.7
      5: 0.19.8
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 40
eta:
  desc: null
  value: 0.0008086816079827695
hidden_size:
  desc: null
  value: 64
num_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: nadam
weight_decay:
  desc: null
  value: 0
weight_init:
  desc: null
  value: random
