wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
eta:
  value: 0.0004081808461689877
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0.0001
weight_init:
  value: Xavier
