wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 40
eta:
  value: 0.0008086816079827695
hidden_size:
  value: 64
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
