wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 20
eta:
  value: 0.0008991969030621379
hidden_size:
  value: 32
num_layers:
  value: 2
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: random
