wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 40
eta:
  value: 0.000834178071109891
hidden_size:
  value: 32
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
