wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.0005598639899007759
hidden_size:
  value: 64
num_layers:
  value: 2
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: Xavier
