wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.19.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744342546
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 14
      - 17
      - 23
      - 37
      4: 3.12.7
      5: 0.19.8
      8:
      - 3
      - 5
      13: windows-amd64
activation:
  desc: null
  value: ReLu
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 20
eta:
  desc: null
  value: 0.0009403515614913782
hidden_size:
  desc: null
  value: 16
num_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0.0005
weight_init:
  desc: null
  value: Xavier
