wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 40
eta:
  value: 0.0008791612437886779
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: random
