wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 20
eta:
  value: 0.0006935516897661284
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0.0001
weight_init:
  value: random
