wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
eta:
  value: 0.000587948450732994
hidden_size:
  value: 16
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: Xavier
