wandb_version: 1

activation:
  value: ReLu
batch_size:
  value: 128
epochs:
  value: 40
eta:
  value: 0.0005252428177565113
hidden_size:
  value: 64
num_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
